<a href="https://colab.research.google.com/github/vivekgautamgv/Python-For-Finance/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
stock_list = [3.5,5,2,8,4.2]

In [3]:
returns = np.array(stock_list)
print(returns,type(returns))

[3.5 5.  2.  8.  4.2] <class 'numpy.ndarray'>


In [4]:
A = np.array([[1,2],[3,4]])
print(A,type(A))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [5]:
print(A.shape)

(2, 2)


In [6]:
print(returns[1:3])

[5. 2.]


Functions built into NumPy can be easily called on arrays. Most functions are applied to an array element-wise (as scalar multiplication is). For example, if we call log() on an array, the logarithm will be taken of each element.

In [7]:
print(np.log(returns))

[1.25276297 1.60943791 0.69314718 2.07944154 1.43508453]


Some functions return a single value. This is because they treat the array as a collection (similar to a list), performing the designated function. For example, the mean() function will do exactly what you expect, calculating the mean of an array.